#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
#python manage.py runserver_plus 0.0.0.0:8000  # works only for the WSGI type requests
daphne -b 0.0.0.0 -p 8000 config.asgi:application  # works both for the WSGI and ASGI type requests
