WS_UNRECOGNIZED = 0

WS_CONNECTED = 1
WS_DISCONNECTED = 2
WS_DENIED = 3

LEVEL_TYPE_SUCCESS = 4
LEVEL_TYPE_WARNING = 5
LEVEL_TYPE_ERROR = 6

FRAME_ACTION_STARTED = 7
FRAME_ACTION_PAUSED = 8
FRAME_ACTION_RESUMED = 9
FRAME_ACTION_COMPLETED = 10
FRAME_ACTION_TERMINATED = 11
FRAME_ACTION_FORCE_TERMINATED = 12

WS_CONNECTION_STATUS = {
    WS_UNRECOGNIZED: 'UNRECOGNIZED',
    WS_CONNECTED: 'CONNECTED',
    WS_DISCONNECTED: 'DISCONNECTED',
    WS_DENIED: 'DENIED'
}

MESSAGE_LEVEL_CHOICES = {
    LEVEL_TYPE_SUCCESS: 'SUCCESS',
    LEVEL_TYPE_WARNING: 'WARNING',
    LEVEL_TYPE_ERROR: 'ERROR'
}

MESSAGE_FRAME_ACTION_CHOICES = {
    FRAME_ACTION_STARTED: 'STARTED',
    FRAME_ACTION_PAUSED: 'PAUSED',
    FRAME_ACTION_RESUMED: 'RESUMED',
    FRAME_ACTION_COMPLETED: 'COMPLETED',
    FRAME_ACTION_TERMINATED: 'TERMINATED',
    FRAME_ACTION_FORCE_TERMINATED: 'FORCE_TERMINATED'
}
