from django.utils.translation import gettext as _

ERROR_UNRECOGNIZED = 10
ERROR_INCOMPLETE_DATA = 11
ERROR_INVALID_HANDLER = 12
ERROR_INVALID_DATA_TYPE = 13

WS_CONNECTED = 20
WS_DISCONNECTED = 21
WS_DENIED = 22

LEVEL_TYPE_NEUTRAL = 30
LEVEL_TYPE_SUCCESS = 31
LEVEL_TYPE_WARNING = 32
LEVEL_TYPE_ERROR = 33

FRAME_NO_ACTION_TAKEN = 40
FRAME_ACTION_STARTED = 41
FRAME_ACTION_FINISHED = 42
FRAME_ACTION_FORCE_TERMINATED = 43
FRAME_ACTION_ABORTED = 44


ERROR_MESSAGES = {
    ERROR_UNRECOGNIZED: _('Unknown error occurred.'),
    ERROR_INCOMPLETE_DATA: _('Incomplete data received.'),
    ERROR_INVALID_HANDLER: _('The received handler is invalid.'),
    ERROR_INVALID_DATA_TYPE: _('Invalid data type.')
}

WS_CONNECTION_STATUS = {
    WS_CONNECTED: _('CONNECTED'),
    WS_DISCONNECTED: _('DISCONNECTED'),
    WS_DENIED: _('DENIED')
}

MESSAGE_LEVEL_CHOICES = {
    LEVEL_TYPE_SUCCESS: _('SUCCESS'),
    LEVEL_TYPE_WARNING: _('WARNING'),
    LEVEL_TYPE_ERROR: _('ERROR'),
    LEVEL_TYPE_NEUTRAL: _('NEUTRAL'),
}

MESSAGE_FRAME_ACTION_CHOICES = {
    FRAME_NO_ACTION_TAKEN: _('NO_ACTION_TAKEN'),
    FRAME_ACTION_STARTED: _('STARTED'),
    FRAME_ACTION_FINISHED: _('COMPLETED'),
    FRAME_ACTION_FORCE_TERMINATED: _('FORCE_TERMINATED'),
    FRAME_ACTION_ABORTED: _('FRAME_ACTION_ABORTED')
}
