version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_static_files: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pomodorr_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
      - local_static_files:/app/staticfiles
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: pomodorr_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: pomodorr_local_nginx
    depends_on:
      - django
    volumes:
      - local_static_files:/app/staticfiles
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8025:8025"
      - "0.0.0.0:5555:5555"

  mailhog:
    image: mailhog/mailhog:v1.0.0

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: pomodorr_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: pomodorr_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: pomodorr_local_flower
    command: /start-flower
