# Generated by Django 3.0.5 on 2020-04-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevent',
            name='task',
        ),
        migrations.DeleteModel(
            name='Gap',
        ),
        migrations.DeleteModel(
            name='TaskEvent',
        ),
    ]
