# Generated by Django 2.2.11 on 2020-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='priority',
            name='unique_user_priority_level',
        ),
        migrations.AddConstraint(
            model_name='priority',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_user_priority'),
        ),
    ]
