# Generated by Django 3.0.5 on 2020-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200419_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end'),
        ),
    ]
