# Generated by Django 3.0.5 on 2020-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200422_1617'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_project_task',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('status', 0)), fields=('name', 'project'), name='unique_project_task'),
        ),
    ]
