# Generated by Django 3.0.5 on 2020-04-26 09:15

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200424_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18),
        ),
    ]
