# Generated by Django 3.0.5 on 2020-06-03 09:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pomodoro_length', models.DurationField(default=datetime.timedelta(seconds=1500))),
                ('short_break_length', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('long_break_length', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('long_break_after', models.SmallIntegerField(default=3)),
                ('auto_pomodoro_start', models.BooleanField(default=False)),
                ('auto_break_start', models.BooleanField(default=False)),
                ('disable_breaks', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
