# Generated by Django 3.0.5 on 2020-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateframe',
            options={'ordering': ('created',), 'verbose_name': 'Date frame', 'verbose_name_plural': 'Date frames'},
        ),
        migrations.RemoveField(
            model_name='dateframe',
            name='type',
        ),
        migrations.AddField(
            model_name='dateframe',
            name='frame_type',
            field=models.SmallIntegerField(choices=[(0, 'pomodoro'), (1, 'break'), (2, 'pause')], default=0),
            preserve_default=False,
        ),
    ]
