#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
daphne -b 0.0.0.0 -p 8000 config.asgi:application --chdir=/app  # works both for the WSGI and ASGI type requests
